from enum import Enum

class PageType(Enum):
    # COMMON
    LOGIN_PAGE = "LOGIN_PAGE",
    MAIN_MENU_PAGE = "MAIN_MENU_PAGE"
    PROFILE_PAGE = "PROFILE_PAGE",
    CHANGE_PASSWORD_PAGE = "CHANGE_PASSWORD_PAGE",
    SYLLABUS_PAGE = "SYLLABUS_PAGE",


    # STUDENT
    MY_NOTIFICATIONS_PAGE = "MY_NOTIFICATIONS_PAGE",
    TRANSCRIPT_PAGE = "TRANSCRIPT_PAGE",
    ALL_cOURSES_PAGE = "ALL_cOURSES_PAGE",
    SELECTABLE_COURSES_PAGE = "SELECTABLE_COURSES_PAGE",
    SELECTED_COURSES_PAGE = "SELECTED_COURSES_PAGE",
    APPROVED_COURSES_PAGE = "APPROVED_COURSES_PAGE",


    # ADVISOR
    MY_STUDENTS_PAGE = "MY_STUDENTS_PAGE",
    MY_REQUESTS_PAGE = "MY_REQUESTS_PAGE",
    EVALUATE_REQUESTS_PAGE = "EVALUATE_REQUESTS_PAGE",
    SELECTED_STUDENT_REQUEST_PAGE = "SELECTED_STUDENT_REQUEST_PAGE"


    # LECTURER
    MY_COURSES_PAGE = "MY_COURSES_PAGE",
    SELECTED_MY_COURSE_PAGE = "SELECTED_MY_COURSE_PAGE"