package pagePackage;

public enum PageType {
	LOGIN_PAGE,
	
	MAIN_MENU_PAGE_STUDENT,
	ALL_cOURSES_PAGE,
	SELECTABLE_COURSES_PAGE,
	SELECTED_COURSES_PAGE,
	APPROVED_COURSES_PAGE,

	MAIN_MENU_PAGE_ADVISOR,
	MY_STUDENTS,
	MY_REQUESTS,
	EVALUATE_REQUESTS;
}
