from enum import Enum

class FunctionType(Enum):
    #COMMON
	LOGIN = "LOGIN"
	EXIT = "EXIT"
	CHANGE_PAGE = "CHANGE_PAGE"
	LOGOUT = "LOGOUT"
	CHANGE_PASSWORD = "CHANGE_PASSWORD"
	
	# STUDENT
	READ_NOTIFICATIONS = "READ_NOTIFICATIONS"
	SELECT_COURSE = "SELECT_COURSE"
	DROP_COURSE = "DROP_COURSE"
	SEND_APPROVE = "SEND_APPROVE"
	
	# ADVISOR
	SELECET_STUDENT = "SELECET_STUDENT"
	APPROVE_REQUEST = "APPROVE_REQUEST"
	DISAPPREOVE_REQUEST = "DISAPPREOVE_REQUEST"
	
	# LECTURER
	SELECT_MY_COURSE = "SELECT_MY_COURSE"
