package Page;

public enum PageType {
	// COMMON
	LOGIN_PAGE,
	CHANGE_PASSWORD_PAGE,
	
	// STUDENT
	MAIN_MENU_PAGE_STUDENT,
	PROFILE_PAGE_STUDENT,
	MY_NOTIFICATIONS,
	ALL_cOURSES_PAGE,
	SELECTABLE_COURSES_PAGE,
	SELECTED_COURSES_PAGE,
	APPROVED_COURSES_PAGE,
	SYLLABUS_PAGE_STUDENT,

	// ADVISOR
	MAIN_MENU_PAGE_ADVISOR,
	PROFILE_PAGE_ADVISOR,
	MY_STUDENTS_PAGE,
	MY_REQUESTS_PAGE,
	EVALUATE_REQUESTS_PAGE,
	SELECTED_STUDENT_REQUEST_PAGE,
	
	// LECTURER
	MAIN_MENU_PAGE_LECTURER,
	PROFILE_PAGE_LECTURER,
	MY_COURSES_PAGE,
	SELECTED_MY_COURSE_PAGE;
}
