package Page;

public enum PageType {
	// COMMEN
	LOGIN_PAGE,
	
	// STUDENT
	MAIN_MENU_PAGE_STUDENT,
	ALL_cOURSES_PAGE,
	SELECTABLE_COURSES_PAGE,
	SELECTED_COURSES_PAGE,
	APPROVED_COURSES_PAGE,

	// ADVISOR
	MAIN_MENU_PAGE_ADVISOR,
	MY_STUDENTS_PAGE,
	MY_REQUESTS_PAGE,
	EVALUATE_REQUESTS_PAGE,
	SELECTED_STUDENT_REQUEST_PAGE;
}
